.eslintrc.json, package.json, src/App.test.tsx, src/App.tsx
- add eslint settings
- import 시에 file suffix 제거
- 기명 함수 선언식 컴포넌트, 기명 화살표 함수 컴포넌트 사용
- 환경변수 test value 제거
=> Feat eslint settings

.eslintignore, .eslintrc.json, craco.config.js
- eslintignore 추가
- craco.config
- import/core-modules 등록
- notistack, styled-reset
=> 🚧[setting] eslint settings #10

package-lock.json, package.json, src/App.tsx, src/api/signUpApi.ts, src/env.ts, src/hooks/useAlert.ts, src/index.tsx, src/pages/SignUp.tsx
- 회원가입 페이지 와이어프레임 개발
- 회원가입 기능 연동
- 회원 정보 입력에 대한 유효성 검사 진행 필요 -> 이슈로 등록
- notistack 라이브러리 추가
- Snackbar 사용 편의성을 위해 useAlert Hook 작성
- src/env.ts : 환경변수 사용 파일 생성
=> 회원가입 페이지 / 기능 개발

package-lock.json, package.json, src/App.tsx, src/Layouts/Layout.css, src/Layouts/UserLayout.tsx, src/components/Header/Header.tsx, src/components/Header/Nav.tsx, src/components/Header/SearchInput.tsx, src/components/Header/UserInfo.tsx, src/pages/Home.tsx
=> Header 컴포넌트 스타일 적용

.gitmodules
before: src/config
after : src/_config
src 디렉토리의 최상단으로 끌어올리기 위함
=> env submodule 네이밍 수정

.gitmodules
- 디렉토리 변경 후 dev 브랜치에서 정보를 못 읽어오는 현상 발생
- 이에 따른 merge 취소
=> 서브모듈 디렉토리 변경 취소

package-lock.json, src/components/Header/SearchInput.tsx
- Header 컴포넌트 스타일 적용
- 검색창 검색 옵션 스타일 적용
=> Header 검색창 검색옵션 스타일 적용 

src/Layouts/Layout.css, src/Layouts/UserLayout.tsx, src/components/Header/SearchInput.tsx, src/components/Sidebar/Sidebar.css, src/components/Sidebar/Sidebar.tsx
- Sidebar 컴포넌트 마크업 및 스타일(위치) 적용
- 사용하지 않은 import 제거
=> Sidebar 컴포넌트 마크업 및 스타일 적용

src/api/projectApi.ts, src/components/modal/project/CreateProjectModal.tsx
- 프로젝트 추가 모달
- 공통 컴포넌트 모달 적용
- hooks 적용
=> 리팩토리 프로젝트 생성 모달

src/components/common/CustomModal.tsx, src/components/modal/workspace/WorkspaceManageModal.tsx, src/components/modal/workspace/page/WorkspaceDataManage.tsx, src/components/modal/workspace/page/WorkspaceParticipantManage.tsx, src/store/taskTableStore.ts
- 일부 미완료
- 워크스페이스 삭제
- 워크스페이스 참여자 목록 (조회 및 권한 변경, 내보내기)
=> Feat workspace admin modal

src/components/common/Menu.tsx, src/components/sidebar/IconBtn.tsx, src/components/sidebar/Sidebar.tsx
- selected 효과 수정
- IconBtn 컴포넌트 적용
=> 사이드바(LNB) 마크업 및 스타일

src/_types/ProjectType.ts, src/_types/TaskType.ts, src/_types/WorkspaceType.ts, src/api/index.ts, src/api/projectApi.ts, src/api/taskApi.ts, src/api/workspaceApi.ts, src/components/common/SelectListButton.tsx, src/components/common/TextFieldBox.tsx, src/components/modal/task/TaskCreateModal.tsx, src/components/modal/task/TaskDetailModal.tsx, src/components/task/BoardSelectButton.tsx, src/components/task/ProgressSelectButton.tsx, src/components/task/ProjectSelectButton.tsx, src/components/task/kanban/TaskCard.tsx, src/components/task/kanban/TaskKanbansWrapper.tsx, src/components/task/table/TaskCell.tsx, src/components/task/table/TaskTableWrapper.tsx
- 할 일 생성 기능 개발
- 할 일 단건 조회 기능 개발
- 할 일 수정 기능 개발
=> ❇️[feat] 할 일 생성 및 수정, 단건 조회 개발 #72, #73, #74

src/api/projectApi.ts, src/components/common/CalendarDateField.tsx, src/components/modal/project/ProjectParticipantsModal.tsx, src/components/modal/task/TaskCreateModal.tsx, src/components/modal/task/TaskDetailModal.tsx
- 프로젝트 참여자 목록 조회 API 작성
- 프로젝트 참여자 목록 조회 모달 개발
- 할 일 생성, 할 일 수정시 프로젝트 참여자 목록 모달 오픈, 선택 가능
=> ❇️[feat] 프로젝트 참여자 목록 조회 #72, #73, #74

src/_types/workspace/index.ts, src/api/workspace/index.ts, src/components/common/EditableBox.tsx, src/components/common/SelectListButton.tsx, src/components/common/TitleModal.tsx, src/components/image/ImageInput.tsx, src/components/workspace/WorkspaceDataManage.tsx, src/components/workspace/WorkspaceParticipantManage.tsx, src/components/workspace/WorkspaceProfileManage.tsx, src/components/workspace/modal/MemberInviteModal.tsx, src/components/workspace/modal/WorkspaceSettingsModal.tsx, src/pages/workspace/index.tsx
#89 
- edit 가능한 Box Component
- 제목 보유한 Modal(MUI Dialog)
- 워크스페이스 기본 정보 조회 및 수정 기능 개발
- 내 워크스페이스 프로필 정보 조회 및 수정 기능 개발
- 워크스페이스 참여자 관리 기능 개발
- 참여자 목록 조회 기능 개발
- 참여자 권한 변경 기능 개발
- 참여자 초대 기능 개발
- 워크스페이스 참여자 강퇴, 워크스페이스 탈퇴 및 삭제 기능은 백엔드 기능 개발 완료 후 개발 예정
=> 워크스페이스 설정 개발 #89

src/components/workspace/WorkspaceDataManage.tsx, src/components/workspace/WorkspaceParticipantManage.tsx
- 워크스페이스 설정 모달 개발 완료
- 워크스페이스 탈퇴/삭제 기능 개발
- 워크스페이스 참여자 강퇴 기능 개발
=>  ❇️[feat] 워크스페이스 설정 모달 개발 완료 #89

src/components/common/EditableBox.tsx, src/components/project/ProjectGeneralSetting.tsx, src/components/workspace/InputWorkspaceInfo.tsx, src/components/workspace/InputWsProfileInfo.tsx, src/components/workspace/WorkspaceDataManage.tsx, src/components/workspace/WorkspaceProfileManage.tsx, src/components/workspace/modal/CreateWorkspaceModal.tsx
=> FIX: issue #98

src/components/project/modal/CreateProjectModal.tsx, src/pages/workspace/WorkspaceMain.tsx
- TitleModal로 수정
- 유효성 검사
- 생성 시 re-rendering 되도록 수정
=> 🔨[refactor] 프로젝트 생성 모달 리팩토링

.eslintrc.json, src/components/common/TitleModal.tsx, src/components/project/modal/ProjectParticipantsModal.tsx, src/components/task/modal/TaskCreateModal.tsx
=> Fix task create

src/components/common/EditableBox.tsx, src/components/common/SelectListButton.tsx, src/components/common/TitleModal.tsx, src/components/project/modal/ProjectParticipantsModal.tsx, src/components/task/kanban/TaskCard.tsx, src/components/task/modal/TaskDetailModal.tsx
=> Fix task detail. issue #104

src/components/common/CreateBtn.tsx, src/components/common/Menu.tsx, src/components/header/Header.tsx, src/components/header/Nav.tsx, src/components/sidebar/IconBtn.tsx, src/components/sidebar/MenuItems.tsx, src/components/sidebar/Sidebar.tsx, src/components/sidebar/SidebarMenu.tsx, src/components/sidebar/WorkspaceProfile.tsx, src/layouts/UserLayout.tsx, src/pages/workspace/WorkspaceMain.tsx
=> Sidebar 디자인 적용

src/components/common/CalendarDateField.tsx, src/components/task/modal/TaskCreateModal.tsx, src/components/task/modal/TaskDetailModal.tsx, src/components/task/table/TaskCell.tsx, src/components/workspace/WorkspaceProfileModify.tsx, src/pages/Home.tsx, src/pages/Landing.tsx
- 할 일 생성 모달 열리지 않는 문제 해결
- 테이블 뷰에서 칸반 뷰로 이동시 오류 발생하는 문제 해결
- 프로필 수정 모달 열리지 않는 문제 해결
=> 🐞[fix] hotfix

src/_types/TaskTimelineType.ts, src/components/task/timeline/TaskTimelineBar.tsx, src/components/task/timeline/TaskTimelineView.tsx, src/store/taskTimelineStore.ts, src/utils/DateUtils.ts
=> ❇️[feat] 할 일 목록 조회 타임라인 뷰 개발 #124

package-lock.json, package.json, src/components/header/Header.tsx, src/components/header/Nav.tsx, src/components/header/SearchInput.tsx, src/components/sidebar/IconBtn.tsx, src/components/sidebar/IconBtnWrapper.tsx, src/components/sidebar/MenuItems.tsx, src/components/sidebar/Sidebar.tsx, src/components/sidebar/SidebarMenu.tsx, src/components/sidebar/SubIconBtn.tsx, src/components/sidebar/WorkspaceProfile.tsx, src/components/task/history/TaskHistoriesWrapper.tsx, src/components/task/timeline/TaskTimelineView.tsx, src/components/workspace/main/WorkspaceDeadlineTaskWrapper.tsx, src/components/workspace/main/WorkspaceNotice.tsx, src/components/workspace/main/WorkspaceParticipants.tsx, src/layouts/UserLayout.tsx, src/pages/workspace/WorkspaceMain.tsx
=> 사이드바 , 워크스페이스 메인, 헤더 스타일

src/components/task/TaskView.tsx, src/components/task/timeline/TaskTimelineView.tsx
=> 🐞[fix] 할 일 목록 조회 오류 수정

src/components/task/TaskHeader.tsx, src/pages/workspace/project/index.tsx
=> Feat tasks filter

src/_types/notification/index.ts, src/api/notification/index.ts, src/components/header/Header.tsx, src/components/header/notification/NotificationButton.tsx, src/hooks/notification/useFetchNotifications.ts, src/hooks/notification/useReadNotification.ts, src/hooks/sse/useNotification.ts, src/pages/workspace/index.tsx, src/store/notificationStore.ts
- #118 
---
- SSE 이용, 특정 이벤트 발생시 해당 notification 저장
- GNB 알림 버튼 클릭시 알림 목록 리스트 출력
=> GNB 알림 기능 구현

src/_types/notification/index.ts, src/api/notification/index.ts, src/components/header/Header.tsx, src/components/header/notification/NotificationButton.tsx, src/components/workspace/JoinWorkspace.tsx, src/hooks/notification/useFetchNotifications.ts, src/hooks/notification/useReadNotification.ts, src/hooks/sse/useNotification.ts, src/hooks/workspace/useJoinWorkspace.ts, src/pages/workspace/index.tsx, src/store/notificationStore.ts
- #148
---
- previous PR : #149
---
- 워크스페이스 초대 알림을 클릭하면 참여 모달이 open 되도록 구현
- 참여 완료시 알림 삭제
- 추후 거절 API 및 버튼을 넣어서 참여 안하고도 삭제할 수 있도록 개선하면 좋을 것 같음
=> 워크스페이스 참여 페이지 개발

.eslintrc.json, src/_types/style/index.ts, src/components/common/ColorAvatar.tsx, src/components/common/EditableTextBox.tsx, src/components/common/MenuModal.tsx, src/components/common/TitleDialog.tsx, src/components/header/notification/NotificationButton.tsx, src/components/image/ImageInput.tsx, src/components/project/ProjectGeneralSetting.tsx, src/components/project/ProjectParticipantsSetting.tsx, src/components/project/invite/ProjectInvite.tsx, src/components/sidebar/WorkspaceProfile.tsx, src/components/task/modal/TaskDetailModal.tsx, src/components/workspace/WorkspaceDataManage.tsx, src/components/workspace/WorkspaceParticipantManage.tsx, src/components/workspace/WorkspaceProfileModify.tsx, src/components/workspace/WorkspaceSelectButton.tsx, src/components/workspace/invite/MemberInvite.tsx, src/components/workspace/main/WorkspaceParticipants.tsx, src/components/workspace/modal/WorkspaceSettingsModal.tsx, src/components/workspace/role/RoleButton.tsx, src/components/workspace/role/SelectRoleButton.tsx, src/pages/SignUp.tsx, src/pages/workspace/index.tsx
- TitleDialog 제목 스타일 수정
- 역할 표시 버튼 스타일 수정
=> 💄[style] 역할 버튼 및 TitleDialog 스타일 수정

src/App.tsx, src/components/task/history/TaskHistory.tsx, src/components/task/kanban/TaskCard.tsx, src/components/task/modal/TaskDetailModal.tsx, src/components/task/reply/TaskReplyItem.tsx, src/components/task/table/TaskCell.tsx
- 할 일 목록, 할 일 상세에서 참여자 아바타 컴포넌트 변경
=> 할 일 - 참여자 아바타 스타일 변경

src/components/common/NoData.tsx, src/components/project/CreateProject.tsx, src/components/project/modal/ProjectParticipantsModal.tsx, src/components/sidebar/SidebarMenu.tsx, src/components/task/BoardSelectButton.tsx, src/components/task/CreateTask.tsx, src/components/task/ProjectSelectButton.tsx, src/components/task/modal/TaskCreateModal.tsx, src/components/task/modal/TaskDetailModal.tsx, src/hooks/project/useCreateBoard.ts, src/hooks/project/useCreateProject.ts
=> 🐞[fix] 할 일 생성 Empty-SET #198

src/components/member/EmailInfoSection.tsx, src/components/member/MemberInfoSection.tsx, src/components/member/modal/AddEmailModal.tsx, src/components/member/modal/CheckPasswordModal.tsx, src/components/message/MessageListSection.tsx, src/components/message/ReadMessageSection.tsx, src/components/message/SendMessageSection.tsx, src/hooks/member/useEmailCheck.ts
=> 🔨[refactor] email-modal-issue #197

src/components/task/reply/TaskReplyInput.tsx, src/components/workspace/main/WorkspaceParticipants.tsx
=> Fix issue#220

src/components/project/modal/ProjectSettingsModal.tsx, src/components/task/timeline/TaskTimelineView.tsx, src/components/workspace/ParticipantsModal.tsx, src/components/workspace/WorkspaceSelectButton.tsx, src/components/workspace/modal/WorkspaceSettingsModal.tsx, src/components/workspace/settings/WorkspaceProfileManage.tsx, src/hooks/task/useHandleBookmark.ts, src/hooks/workspace/useRemoveWorkspace.ts, src/hooks/workspace/useWithdrawWorkspace.ts
=> 워크스페이스 탈퇴, 삭제 시점 GNB 워크스페이스 목록 싱크 문제 해결 #185

src/components/message/SelectReceiverButton.tsx, src/components/message/SendMessageSection.tsx
- 쪽지 받는이 수정  (히든처리, width)
- 쪽지 받는이 프로필아이콘 변경
=> 쪽지 모달 디테일 수정

src/components/notification/NotificationButton.tsx, src/components/notification/NotificationsReadBox.tsx, src/components/notification/NotificationsUnreadBox.tsx, src/components/workspace/ParticipantsModal.tsx
=> 알림 목록 EmptySet #225

src/components/header/Header.tsx, src/components/member/modal/AddEmailModal.tsx, src/components/search/ProjectSearchResultWrapper.tsx, src/components/search/SearchInput.tsx, src/components/search/SearchResultNav.tsx, src/components/search/TaskSearchResultWrapper.tsx, src/components/search/WorkspaceSearchResultWrapper.tsx, src/components/sidebar/SidebarMenu.tsx, src/components/workspace/WorkspaceSelectButton.tsx, src/hooks/member/useEmailCheck.ts
=> GNB, LNB EMPTY-SET issue#231

src/components/project/ProjectParticipantsSetting.tsx, src/components/project/invite/ProjectInvite.tsx, src/components/workspace/invite/MemberInvite.tsx, src/components/workspace/settings/WorkspaceParticipantManage.tsx, src/hooks/useDebounce.ts
=> 워크스페이스/프로젝트 설정 EmptySet issue#237

src/auth/RefreshComponent.tsx, src/components/task/TaskView.tsx, src/hooks/auth/useSignIn.ts, src/hooks/member/useEmailCheck.ts, src/hooks/member/useSignUp.ts, src/pages/SignIn.tsx, src/pages/SignUp.tsx
- 할 일 목록 페이지 EmptySet 추가
- 로그인 오류 처리 추가
- 회원가입 페이지 스타일 변경
- 버튼 색 변경
- 이메일 전송 로딩 추가
=> 할 일 목록 EmptySet, 로그인 오류 처리 추가, 회원가입 페이지 스타일 변경 issue#171

src/_types/notification/index.ts, src/api/task/index.ts, src/components/notification/card/RegisteredTaskManager.tsx, src/components/search/result/TaskSearchResult.tsx, src/components/task/TaskView.tsx, src/components/task/deadlined/DeadlineTask.tsx, src/components/task/history/TaskHistory.tsx, src/components/task/kanban/TaskCard.tsx, src/components/task/kanban/TaskKanbansWrapper.tsx, src/components/task/modal/TaskDetailModal.tsx, src/components/task/reply/TaskReply.tsx, src/components/task/reply/TaskReplyInput.tsx, src/components/task/reply/TaskReplyItem.tsx, src/components/task/table/TaskCell.tsx, src/components/task/table/TaskTableWrapper.tsx, src/components/task/timeline/TaskTimelineBar.tsx, src/components/task/timeline/TaskTimelineView.tsx, src/hooks/task/useCreateTask.ts, src/hooks/task/useFetchTaskDetail.ts, src/hooks/task/useFetchTaskHistory.ts, src/hooks/task/useHandleBookmark.ts, src/hooks/task/useModifyTask.ts, src/hooks/task/useRemoveTask.ts, src/store/taskStore.ts, src/store/taskTableStore.ts
=> 🐞[fix] 할 일 API 변경 및 스타일 수정 #249

src/components/notification/card/RegisteredTaskManager.tsx, src/components/workspace/main/WorkspaceNotice.tsx, src/components/workspace/modal/WorkspaceNoticeModal.tsx, src/components/workspace/notice/CreateWorkspaceNotice.tsx, src/components/workspace/notice/ModifyWorkspaceNotice.tsx, src/components/workspace/notice/WorkspaceNoticeDetailView.tsx, src/components/workspace/notice/WorkspaceNoticeList.tsx, src/hooks/workspace/useCreateWorkspaceNotice.ts, src/hooks/workspace/useFetchWorkspaceNoticeList.ts, src/hooks/workspace/useModifyWorkspaceNotice.ts, src/pages/SignUp.tsx, src/store/userStore.ts, src/utils/DateUtils.ts
=> Fix issue#254

src/components/task/timeline/TaskTimelineView.tsx
=> 할 일 타임라인뷰 헤더 오류 수정

src/components/common/MainEmpty.tsx, src/components/task/timeline/TaskTimelineView.tsx, src/components/workspace/main/WorkspaceDeadlineTaskWrapper.tsx, src/components/workspace/main/WorkspaceNotice.tsx, src/layouts/UserLayout.tsx, src/pages/workspace/WorkspaceMain.tsx
=> Fix issue#261

src/components/common/CalendarDateField.tsx, src/components/common/EditableTextBox.tsx, src/components/task/BoardSelectButton.tsx, src/components/task/modal/TaskDetailModal.tsx, src/components/task/reply/TaskReplyItem.tsx, src/components/workspace/invite/MemberInvite.tsx, src/hooks/task/useFetchTaskHistory.ts, src/hooks/task/useHandleBookmark.ts, src/hooks/task/useModifyTask.ts, src/hooks/task/useRemoveTask.ts
- 보드 선택 버튼 스타일 수정
- 날짜 선택 글자크기 수정
- 댓글 Width 수정
Before
After
=> 할 일 상세 모달 수정

src/components/task/TaskHeader.tsx, src/components/task/kanban/TaskKanbansWrapper.tsx, src/store/taskStore.ts
- 워크스페이스 관리자만 관리자 모드가 보임 
- 담당자가 없는 할일 목록만 보임 
- check box는 워크스페이스 관리자의 아이콘 색깔과 맞춤
- 툴팁 설명
=> 관리자 할일 View

src/components/sidebar/IconBtnWrapper.tsx, src/hooks/workspace/useWithdrawWorkspace.ts
워크스페이스 탈퇴시 간헐적으로 404 오류 발생하는 문제 해결
=> 🐞[fix] 워크스페이스 탈퇴시 404 오류 해결

src/components/project/ProjectParticipantsSetting.tsx, src/components/sidebar/SidebarMenu.tsx, src/components/workspace/ParticipantsModal.tsx
- 디바운스 적용 - 재윤 (0.5초)
- 워크스페이스 설정 - 구성원 관리 - 참여자 검색
- 프로젝트 목록 검색
- 구성원 보기 - 참여자 검색
=> 검색 애들 디바운스 적용
